// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm1EKIiiPZfWZpoUYMl_pYjwu34jZzGLY',
    appId: '1:165864642375:web:132648214f81131a059e62',
    messagingSenderId: '165864642375',
    projectId: 'first-qdthq8',
    authDomain: 'first-qdthq8.firebaseapp.com',
    storageBucket: 'first-qdthq8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyboZ5DFsjfJSpioqHFN3aop3WL0hvn6I',
    appId: '1:165864642375:android:676ca5411c0a6ffc059e62',
    messagingSenderId: '165864642375',
    projectId: 'first-qdthq8',
    storageBucket: 'first-qdthq8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SisXXNOU4rt_a6NCnceJNVa8w-mginY',
    appId: '1:165864642375:ios:0c501a2e44eba5de059e62',
    messagingSenderId: '165864642375',
    projectId: 'first-qdthq8',
    storageBucket: 'first-qdthq8.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractise1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SisXXNOU4rt_a6NCnceJNVa8w-mginY',
    appId: '1:165864642375:ios:0c501a2e44eba5de059e62',
    messagingSenderId: '165864642375',
    projectId: 'first-qdthq8',
    storageBucket: 'first-qdthq8.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractise1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm1EKIiiPZfWZpoUYMl_pYjwu34jZzGLY',
    appId: '1:165864642375:web:d3d18c533ddc785e059e62',
    messagingSenderId: '165864642375',
    projectId: 'first-qdthq8',
    authDomain: 'first-qdthq8.firebaseapp.com',
    storageBucket: 'first-qdthq8.firebasestorage.app',
  );

}